[tool.poetry]
name = "conf-parsers"
version = "0.1.0"
description = ""
authors = ["Nyaaa <1457047+Nyaaa@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
beautifulsoup4 = "^4.12.2"
selenium = "^4.9.1"
scrapy = "^2.9.0"
asyncpg = "^0.27.0"
sqlalchemy = "^2.0.15"
dateparser = "^1.1.8"


[tool.poetry.group.dev.dependencies]
aiosqlite = "^0.19.0"
webdriver-manager = "^3.8.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
