[tool.poetry]
name = "conf-parsers"
version = "1.0.0"
description = "The Conf parsing service"
authors = ["Nyaaa <1457047+Nyaaa@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
scrapy = "^2.9.0"
sqlalchemy = "^2.0.15"
dateparser = "^1.1.8"
psycopg = {extras = ["binary"], version = "^3.1.9"}
scrapy-playwright = "^0.0.26"
pdfplumber = "^0.9.0"


[tool.poetry.group.dev.dependencies]
ipython = "^8.14.0"


[tool.poetry.group.tests.dependencies]
coverage = "^7.2.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
branch = true
#source = ['conf_parsers']
include = ['conf_parsers/*']
omit = ['settings.py']

[tool.coverage.report]
skip_covered = true
