version: '3.8'

services:

  db:
    build: ./pgsql
    container_name: app_db
    volumes:
      - ./pg_data:/var/lib/postgresql/data/
    env_file:
      /root/.docker_env
    restart: always

  django:
    build: ./django
    container_name: app_django
    command: gunicorn Conferences.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d/
      - ./django/app:/app/
    expose:
      - 8000
    env_file:
      - /root/.docker_env
    restart: always
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: app_nginx
    ports:
      - "80:80"
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx_conf:/etc/nginx/conf.d/
    depends_on:
      - django
    restart: always
    