version: '3.8'

services:

  db:
    image: postgres:latest
    container_name: app_db
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      /root/.docker_env
    restart: always

  gunicorn:
    build: ./gunicorn
    container_name: app_gunicorn
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/app/static/
      - media:/app/media/
    expose:
      - 8000
    env_file:
      - /root/.docker_env
    restart: always
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: app_nginx
    ports:
      - "80:80"
    volumes:
      - static:/app/static
      - media:/app/media
      - nginx_conf:/etc/nginx/conf.d/
    depends_on:
      - gunicorn
    restart: always

volumes:
  pg_data:
  static:
  media:
  nginx_conf:

