version: '3.8'

services:

  db:
    build: ./pgsql
    container_name: app_db
    volumes:
      - ./pg_data:/var/lib/postgresql/data/
    env_file:
      /root/.env
    restart: always
    networks:
      - backend

  django:
    build: ./django
    container_name: app_django
    entrypoint: /start/run.sh
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d/
      - ./django/app:/app/
      - /etc/letsencrypt:/etc/letsencrypt:ro
    expose:
      - "8000"
    restart: always
    depends_on:
      - db
      - redis
    networks:
      - frontend
      - backend

  nginx:
    image: nginx:latest
    container_name: app_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx_conf:/etc/nginx/conf.d/
      - ./certbot:/var/www/certbot:rw
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - django
    restart: always
    networks:
      - frontend

  redis:
    image: redis:latest
    container_name: app_redis
    volumes:
      - ./redis_data:/data
    restart: always
    networks:
      - backend

networks:
  frontend:
  backend:
    