# Generated by Django 4.1.6 on 2023-02-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf_id', models.CharField(max_length=200, unique=True)),
                ('hash', models.CharField(max_length=200)),
                ('un_name', models.CharField(max_length=300)),
                ('local', models.BooleanField()),
                ('reg_date_begin', models.CharField(blank=True, max_length=200)),
                ('reg_date_end', models.CharField(blank=True, max_length=200)),
                ('conf_date_begin', models.CharField(blank=True, max_length=200)),
                ('conf_date_end', models.CharField(blank=True, max_length=200)),
                ('conf_card_href', models.SlugField(blank=True)),
                ('reg_href', models.SlugField(blank=True)),
                ('conf_name', models.TextField(blank=True)),
                ('conf_s_desc', models.TextField(blank=True)),
                ('conf_desc', models.TextField(blank=True)),
                ('org_name', models.TextField(blank=True)),
                ('themes', models.TextField(blank=True)),
                ('online', models.BooleanField()),
                ('conf_href', models.SlugField(blank=True)),
                ('offline', models.BooleanField()),
                ('conf_address', models.TextField(blank=True)),
                ('contacts', models.TextField(blank=True)),
                ('rinc', models.BooleanField()),
                ('data', models.JSONField()),
            ],
        ),
    ]
