# Generated by Django 4.1.6 on 2023-03-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf_id', models.TextField(unique=True)),
                ('hash', models.CharField(max_length=500)),
                ('un_name', models.CharField(max_length=500, verbose_name='ВУЗ')),
                ('local', models.BooleanField()),
                ('reg_date_begin', models.DateField(blank=True, null=True, verbose_name='Начало регистрации')),
                ('reg_date_end', models.DateField(blank=True, null=True, verbose_name='Окончание регистрации')),
                ('conf_date_begin', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('conf_date_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('conf_card_href', models.URLField(blank=True, max_length=500, verbose_name='Карточка конференции')),
                ('reg_href', models.URLField(blank=True, max_length=500, verbose_name='Ссылка на регистрацию')),
                ('conf_name', models.TextField(blank=True, verbose_name='Название')),
                ('conf_s_desc', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('conf_desc', models.TextField(blank=True, verbose_name='Описание')),
                ('org_name', models.TextField(blank=True, verbose_name='Организатор')),
                ('themes', models.TextField(blank=True, verbose_name='Тематика (от организатора)')),
                ('online', models.BooleanField()),
                ('conf_href', models.URLField(blank=True, max_length=500, verbose_name='Ссылка')),
                ('offline', models.BooleanField()),
                ('conf_address', models.TextField(blank=True, verbose_name='Адрес')),
                ('contacts', models.TextField(blank=True, verbose_name='Контакты')),
                ('rinc', models.BooleanField(verbose_name='РИНЦ')),
                ('data', models.JSONField(blank=True, null=True)),
                ('checked', models.BooleanField(default=False, verbose_name='Проверено')),
                ('tags', models.ManyToManyField(blank=True, to='Conference_data.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Конференция',
                'verbose_name_plural': 'Конференции',
            },
        ),
    ]
