# Generated by Django 4.1.6 on 2023-02-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conference_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='conf_id',
            field=models.TextField(max_length=200, unique=True),
        ),
    ]
