# Generated by Django 4.1.6 on 2023-02-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conference_data', '0002_alter_conference_conf_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='conf_date_begin',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='conference',
            name='conf_date_end',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='conference',
            name='conf_id',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='hash',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='conference',
            name='reg_date_begin',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='conference',
            name='reg_date_end',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
