# Generated by Django 4.1.6 on 2023-02-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conference_data', '0003_alter_conference_conf_date_begin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='conf_card_href',
            field=models.SlugField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='conference',
            name='conf_date_begin',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='conference',
            name='conf_date_end',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='conference',
            name='conf_href',
            field=models.SlugField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='conference',
            name='hash',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='conference',
            name='reg_date_begin',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='conference',
            name='reg_date_end',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='conference',
            name='reg_href',
            field=models.SlugField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='conference',
            name='un_name',
            field=models.CharField(max_length=500),
        ),
    ]
