# Generated by Django 4.1.6 on 2023-02-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conference_data', '0004_alter_conference_conf_card_href_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={'verbose_name': 'Конференция', 'verbose_name_plural': 'Конференции'},
        ),
        migrations.AddField(
            model_name='conference',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
