# Generated by Django 4.1.6 on 2023-03-26 20:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conference_data', '0004_alter_conference_conf_s_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='generate_conf_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conference',
            name='conf_s_desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
    ]
