# Generated by Django 4.1.6 on 2023-02-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conference_data', '0005_alter_conference_options_conference_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Проверено контент-менеджером'),
        ),
    ]
