# Generated by Django 4.1.6 on 2023-02-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conference_data', '0007_tag_conference_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='conf_card_href',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='conference',
            name='conf_href',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='conference',
            name='reg_href',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
