# Generated by Django 4.1.6 on 2023-05-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conference_data', '0007_conference_test2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='test',
            new_name='scopus',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='test2',
        ),
        migrations.AddField(
            model_name='conference',
            name='vak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conference',
            name='wos',
            field=models.BooleanField(default=False),
        ),
    ]
