# Generated by Django 4.1.6 on 2023-02-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conference_data', '0008_alter_conference_conf_card_href_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='conf_date_begin',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='conf_date_end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='reg_date_begin',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='reg_date_end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Conference_data.tag'),
        ),
    ]
