# Generated by Django 4.2.4 on 2023-08-29 17:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conference_data', '0009_favorite_favorite_unique_user_content_type_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='conf_card_href',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на источник'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='conf_href',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Сайт конференции'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='offline',
            field=models.BooleanField(default=True, verbose_name='Оффлайн'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='online',
            field=models.BooleanField(default=False, verbose_name='Онлайн'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='scopus',
            field=models.BooleanField(default=False, verbose_name='Scopus'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='vak',
            field=models.BooleanField(default=False, verbose_name='ВАК'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='wos',
            field=models.BooleanField(default=False, verbose_name='WoS'),
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf_id', models.TextField(unique=True)),
                ('un_name', models.CharField(max_length=500, verbose_name='ВУЗ')),
                ('local', models.BooleanField(default=True, verbose_name='Международная')),
                ('reg_date_begin', models.DateField(blank=True, null=True, verbose_name='Начало регистрации')),
                ('reg_date_end', models.DateField(blank=True, null=True, verbose_name='Окончание регистрации')),
                ('conf_card_href', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на источник')),
                ('reg_href', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на регистрацию')),
                ('conf_name', models.TextField(verbose_name='Название')),
                ('conf_s_desc', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('conf_desc', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('contacts', models.TextField(blank=True, null=True, verbose_name='Контакты')),
                ('checked', models.BooleanField(default=False, verbose_name='Проверено')),
                ('tags', models.ManyToManyField(blank=True, to='Conference_data.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Грант',
                'verbose_name_plural': 'Гранты',
            },
        ),
    ]
