- name: adding users and ssh public keys
  hosts: all
  vars_files:
    - "./vars/users.yml"
  vars:
    - front: 
      - am
    - back: 
      - kl
      - amc
      - vn
  gather_facts: false
  become: true
  become_user: "root"
  become_method: "sudo"

  tasks:

    - name: Creating new users
      user:
        name: "{{ item.name }}"
        state: present
        shell: "/bin/bash"
        create_home: true
      with_items: 
        - "{{ users }}"

    - name: Set authorized_keys
      authorized_key:
        user: "{{ item.name }}"
        state: present
        key: "{{ lookup('pipe','cat ../.metadata/keys/pub/{{ item.name }}.pub') }}"
      with_items: 
        - "{{ users }}"

    - name: create groups for develops
      group:
        name: "{{ item }}"
        state: present
      with_items:
        - appadmin
        - webadmin

    - name: add front develops to webadmin groups
      user:
        name: "{{ front }}"
        groups: webadmin
        append: true

    - name: add back develops to appadmin groups
      user:
        name: "{{ back }}"
        groups: appadmin
        append: true


