# This playbook for GNU Ubuntu/Debian Linux

- name: preconfig/docker/docker-compose
  hosts: test_sf
  gather_facts: false
  become: true
  become_user: "root"
  become_method: "sudo"

  tasks:

    - name: installing dependeses and tools
      package:
        name:
          - wget
          - curl
          - gcc
          - git
          - gzip
          - unzip
          - openssl
          - certbot
          - ca-certificates
          - apt-transport-https
          - software-properties-common
        state: present
        update_cache: true
      tags:
        - inst

    - name: add docker repo gpg key
      shell:
        cmd: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"

    - name: add docker repo
      shell:
        cmd: 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null'

    - name: install docker
      package:
        name: docker-ce
        state: present
        update_cache: true

    - name: run && enable autostart docker
      systemd:
        name: docker
        state: started
        enabled: true

    - name: download docker compose
      shell:
        cmd: "curl -SL https://github.com/docker/compose/releases/download/v2.16.0/docker-compose-linux-x86_64 -o ./docker-compose"
        chdir: "/usr/bin"

    - name: make docker-compose executable
      file:
        path: "/usr/bin/docker-compose"
        mode: "u+x,g+x"
