- name: renewal settings.py
  hosts: test
  vars:
    - dev_path: /usr/data
  gather_facts: false
  become: true
  become_user: "root"
  become_method: "sudo"
  
  tasks:

    - name: copy settings.py to django (test)
      copy:
        src: "../docker_config/django/settings.py"
        dest: "{{ dev_path }}/django/app/Conferences/"
      when:
        - inventory_hostname in groups ["test"]

    - name: copy settings.py to django (prod)
      copy:
        src: "../docker_config/django-prod/settings.py"
        dest: "{{ dev_path }}/django/app/Conferences/"
      when:
        - inventory_hostname in groups ["prod"]

    - name: copy settings.py to root (test)
      copy:
        src: "../docker_config/django/settings.py"
        dest: "/root/"
      when:
        - inventory_hostname in groups ["test"]

    - name: copy settings.py to root (prod)
      copy:
        src: "../docker_config/django-prod/settings.py"
        dest: "/root/"
      when:
        - inventory_hostname in groups ["prod"]
  

    