- name: default preconfig all nodes
  hosts: all
  gather_facts: false
  become: true
  become_user: "root"
  become_method: "sudo"

  tasks:

    - name: installing dependeses and tools
      package:
        name:
          - wget
          - curl
          - gcc
          - make
          - openssl-devel
          - bzip2-devel
          - certbot-nginx
        state: present
        update_cache: true

    - name: download and unzip binaries python 3.8
      shell:
        cmd: "wget https://www.python.org/ftp/python/3.8.12/Python-3.8.12.tgz && tar xzf ./Python-3.8.12.tgz"
        chdir: /data/distrib

    - name: configuring py binaries
      shell:
        cmd: "./configure --enable-optimizations --prefix=/usr/"
        chdir: /data/distrib/Python-3.8.12

    - name: install python-3.8
      make:
        chdir: /data/distrib/Python-3.8.12
        target: install
  
    - name: installing needed libs
      package:
        name:
          - libselinux-python
          - libselinux-python3
          - epel-release
        state: present
        update_cache: true

    - name: disable SELinux
      selinux:
        state: disabled

    - name: Reboot VM now
      reboot:
        reboot_timeout: 600
