- name: default preconfig node
  hosts: test
  gather_facts: false
  become: true
  become_user: "root"
  become_method: "sudo"

  tasks:

    - name: installing dependeses and tools
      package:
        name:
          - epel-release
          - wget
          - curl
          - gcc
          - make
          - openssl-devel
          - bzip2-devel
        state: present
        update_cache: true
      
    - name: installing certbot
      package:
        name: certbot-nginx
        state: present
        update_cache: true

    - name: creating distrib directory
      file:
        path: /data/distrib
        state: directory
        mode: "0754"

    - name: download and unzip binaries python 3.8
      shell:
        cmd: "wget https://www.python.org/ftp/python/3.8.12/Python-3.8.12.tgz && tar xzf ./Python-3.8.12.tgz"
        chdir: /data/distrib

    - name: configuring py binaries
      shell:
        cmd: "./configure --enable-optimizations --prefix=/usr/"
        chdir: /data/distrib/Python-3.8.12

    - name: install python-3.8
      make:
        chdir: /data/distrib/Python-3.8.12
        target: install
  
    - name: installing needed libs
      package:
        name:
          - libselinux-python
          - libselinux-python3
        state: present
        update_cache: true

    - name: disable SELinux
      selinux:
        state: disabled

    - name: Reboot VM now
      reboot:
        reboot_timeout: 600

    - name: install postgresql and dependeses
      package:
        name:
          - postgresql
          - postgresql-server
          - postgresql-contrib
          - postgresql-libs
          - python3-psycopg2
        state: present
        update_cache: true
      tags:
        - pg

    - name: create pg data directory
      file:
        path: /data/pgsql
        state: directory
        owner: postgres
        group: postgres
        mode: "u=rwx,g=rx,o=rx"
        recurse: true
      tags:
        - pg
    
    - name: stop postgresql demon if it runned
      systemd:
        name: postgresql
        state: stopped
      tags:
        - pg

    - name: postgresql init instance
      shell:
        cmd: "sudo -u postgres /usr/bin/initdb -D /data/pgsql/main"
      tags:
        - pg

    - name: change pg data directory
      lineinfile:
        path: "/lib/systemd/system/postgresql.service"
        search_string: "Environment=PGDATA=/var/lib/pgsql/data"
        line: "Environment=PGDATA=/data/pgsql/main"
      tags:
        - pg

    - name: reload systemctl
      command: "systemctl daemon-reload"
      tags:
        - pg

    - name: start && enable postgresql service
      systemd:
        name: postgresql
        state: started
        enabled: true
      tags:
        - pg

    - name: install nodejs and npm from epel repo, install nginx
      package:
        name:
          - nodejs
          - npm
          - nginx
        state: present
        update_cache: true

    - name: create folders for apps 
      file:
        path: /data/apps
        state: directory
        owner: root
        group: appadmin
        mode: "0664"
        recurse: true

    - name: create folder for site 
      file:
        path: /data/www/default
        state: directory
        owner: root
        group: webadmin
        mode: "0755"
        recurse: true

    - name: copy edited nginx.conf to server
      copy:
        src: "../conf/nginx.conf"
        dest: "/etc/nginx/nginx.conf"
        mode: "0644"
        backup: true

    - name: copy default site config to server
      copy:
        src: "../conf/default.conf"
        dest: "/etc/nginx/conf.d/default.conf"
        mode: "0644"
        backup: true

    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: true

    - name: install fastAPI
      pip:
        name: fastapi
        executable: pip3

    
    