- name: install && preconfig react.js
  hosts: all
  vars:
    - front: am
  gather_facts: false
  become: true
  become_user: "root"
  become_method: "sudo"

  tasks:
  
    - name: add front develops to appadmin and webadmin groups
      user:
        name: "{{ front }}"
        groups: appadmin, webadmin
        append: true

    - name: install fastAPI
      pip:
        name: fastapi
        executable: pip3

    - name: copy edited nginx.conf to server
      copy:
        src: "../conf/nginx.conf"
        dest: "/etc/nginx/nginx.conf"
        mode: "0644"
        backup: true

    - name: restart nginx
      systemd:
        name: nginx
        state: restarted

