- name: install && preconfig react.js
  hosts: all
  vars:
    - front: am
  gather_facts: false
  become: true
  become_user: "root"
  become_method: "sudo"

  tasks:

    - name: install react.js using npm
      npm:
        name: create-react-app
        state: present
        global: true

    - name: add front develops to appadmin and webadmin groups
      user:
        name: "{{ front }}"
        groups: appadmin, webadmin
        append: true

    - name: install fastAPI
      pip:
        name: fastapi
        executable: pip3

